framework:
    router:
        # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
        # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
        # default_uri is optional and can be set via DEFAULT_URI env var if needed
        # default_uri: 'http://localhost:8000'

when@prod:
    framework:
        router:
            strict_requirements: null
